//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaneDevelopment.WPF.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaneDevelopment.WPF.Controls.Properties.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###.
        /// </summary>
        internal static string BadAutoToolTipFormat {
            get {
                return ResourceManager.GetString("BadAutoToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###.
        /// </summary>
        internal static string BadDateTimeTicksFormat {
            get {
                return ResourceManager.GetString("BadDateTimeTicksFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###.
        /// </summary>
        internal static string BadDateTimeTicksValue {
            get {
                return ResourceManager.GetString("BadDateTimeTicksValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###.
        /// </summary>
        internal static string BadDateTimeToStringFormat {
            get {
                return ResourceManager.GetString("BadDateTimeToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###.
        /// </summary>
        internal static string BadLabeledTickFormat {
            get {
                return ResourceManager.GetString("BadLabeledTickFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###.
        /// </summary>
        internal static string BadTimeSpanToStringFormat {
            get {
                return ResourceManager.GetString("BadTimeSpanToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection bad destination array.
        /// </summary>
        internal static string CollectionBadDestArray {
            get {
                return ResourceManager.GetString("CollectionBadDestArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection bad rank.
        /// </summary>
        internal static string CollectionBadRank {
            get {
                return ResourceManager.GetString("CollectionBadRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection bad type.
        /// </summary>
        internal static string CollectionBadType {
            get {
                return ResourceManager.GetString("CollectionBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date, or leave this value blank.
        /// </summary>
        internal static string DateTimeValidationRuleMsg {
            get {
                return ResourceManager.GetString("DateTimeValidationRuleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator collection changed.
        /// </summary>
        internal static string EnumeratorCollectionChanged {
            get {
                return ResourceManager.GetString("EnumeratorCollectionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator not started.
        /// </summary>
        internal static string EnumeratorNotStarted {
            get {
                return ResourceManager.GetString("EnumeratorNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator reached end.
        /// </summary>
        internal static string EnumeratorReachedEnd {
            get {
                return ResourceManager.GetString("EnumeratorReachedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid timespan, or leave this value blank.
        /// </summary>
        internal static string TimeSpanValidationRuleMsg {
            get {
                return ResourceManager.GetString("TimeSpanValidationRuleMsg", resourceCulture);
            }
        }
    }
}
